import { COMPANY_IDS } from './companies'

/**
 * Static snapshot of the 2025 법인세 paperwork stored in the user's Google
 * Drive folder `정주현_법인세_서류_2025`. Generated by enumerating the folder
 * once via the Google Drive integration and committed so the dashboard does
 * not have to call Drive at request time. To refresh, re-run the ingest
 * script / agent task and regenerate this file.
 *
 * Source folder ID: 1YHd0kUpXFwWyf23zfXwWKwpozk3r5Tpr
 */

export type TaxDocument = {
  name: string
  webViewLink: string
  mimeType: string
}

export type TaxDocumentFolder = {
  subfolder: string
  files: TaxDocument[]
}

export const TAX_DOCUMENTS_2025: Record<string, TaxDocumentFolder[]> = {
  [COMPANY_IDS.COD_SPORTS]: [
    { subfolder: '01_씨오디스포츠_법인세신고서', files: [] },
  ],
  [COMPANY_IDS.BNF_SPORTS]: [
    { subfolder: '02_비앤에프스포츠_법인세신고서', files: [] },
  ],
  [COMPANY_IDS.NRD]: [
    { subfolder: '03_엔알디_법인세신고서', files: [] },
  ],
  [COMPANY_IDS.CITY_OF_DREAMS]: [
    {
      subfolder: '04_씨티어브드림즈_법인세신고서',
      files: [
        {
          name: '01 (주)씨티어브드림즈 법인결산 및 세무조정 참고사항 확인 2025.pdf',
          webViewLink: 'https://drive.google.com/file/d/1Era5DiWdWItxAZBTm3OTb19F1FFt9m-r/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '02 (주)씨티어브드림즈 통합 재무상태표 확인 2025.pdf',
          webViewLink: 'https://drive.google.com/file/d/1PnouY8JkNnJz6fvyEbAcQzy_3kdGk7nT/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '03 (주)씨티어브드림즈 통합 손익계산서 확인 2025.pdf',
          webViewLink: 'https://drive.google.com/file/d/1yJeCezXYgFhsAXCB2f4YRrsKMtf5nDr8/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '04 (주)씨티어브드림즈 통합 결산부속명세서 확인 2025.pdf',
          webViewLink: 'https://drive.google.com/file/d/1gtkBc4wnR0s2HxK9Q2V_UIlhrLiOGhGP/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
      ],
    },
  ],
  [COMPANY_IDS.SGD_PARTNERS]: [
    {
      subfolder: '05_에스지디파트너스_법인세납부및신고서',
      files: [
        {
          name: '2025 법인세 납부서(주.에스지디파트너스)_2026.03.31 납기.pdf',
          webViewLink: 'https://drive.google.com/file/d/1BpGVkS7whwP4QG6Q6oW1_8RajWc9yM0C/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '2025 (주)에스지디파트너스 법인세 확인서.pdf',
          webViewLink: 'https://drive.google.com/file/d/1G9-ZiO3cHr4IeWDdhnLcxy8kPDfPKyPM/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '2025 주식등변동상황명세서(주.에스지디파트너스)_직인.pdf',
          webViewLink: 'https://drive.google.com/file/d/1Pw0WpiMwyK5OSfTQ7f6jon41N_nAENSv/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '2025 법인세 신고서(주.에스지디파트너스)_합본.pdf',
          webViewLink: 'https://drive.google.com/file/d/1AvuqK-VBDGwzJ8Jl7jVg-i-oX-_7DOVR/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '2025 계정별 잔액(주.에스지디파트너스 본점)_감사수정 최종본_직인.pdf',
          webViewLink: 'https://drive.google.com/file/d/1qyJWKoJHUBXRI6xnQR8YbiWL5ZqiasyO/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '2025 재무제표 확정_(주)에스지디파트너스(통합)_직인.pdf',
          webViewLink: 'https://drive.google.com/file/d/10H9kTxmCWAhkfyskm-FAXOwPBrHePgD3/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '2025 법인세 분납분 납부서(주.에스지디파트너스)_2026.06.01 납기.pdf',
          webViewLink: 'https://drive.google.com/file/d/1PtoOJxwUrsvuuPoSHpAvpop1Q3dTOcFn/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
      ],
    },
    {
      subfolder: '07_에스지디파트너스_재무제표최종본',
      files: [
        {
          name: '2025 유형자산감가상각비명세서(주.에스지디파트너스 본점)_최종본.pdf',
          webViewLink: 'https://drive.google.com/file/d/1-JCCGMlMXaJCZ3tuwQ2t6Onp4hNdjaHJ/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '2025 손익계산서(주.에스지디파트너스 본점)_감사수정 최종본.pdf',
          webViewLink: 'https://drive.google.com/file/d/1FypUYSB2jdnXwI_8M9yRrL6RHjpdI50X/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '2025 재무상태표(주.에스지디파트너스 본점)_감사수정 최종본.pdf',
          webViewLink: 'https://drive.google.com/file/d/1U2f-60wutTlbK7Ck71mhNsjNrlWCvsSW/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
      ],
    },
  ],
  [COMPANY_IDS.COD_RETAIL]: [
    {
      subfolder: '06_씨오디리테일_법인세신고서',
      files: [
        {
          name: '25년 세무조정 참고사항(리테일).pdf',
          webViewLink: 'https://drive.google.com/file/d/19vK3-nDhWfOUs0rgO2dIBmMbj16ETzOG/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '25년 재무상태표(리테일).pdf',
          webViewLink: 'https://drive.google.com/file/d/1u2wDS86GNo_9wQXsdORdlEJ8B1U30UZo/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '25년 결산부속명세서(리테일).pdf',
          webViewLink: 'https://drive.google.com/file/d/1w-KjJexZLEIfKBgw6_jUit-hF6bIx_2s/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
        {
          name: '25년 손익계산서(리테일).pdf',
          webViewLink: 'https://drive.google.com/file/d/1K2Tdgy190c2P9GiG6yINXAE3GpVtHJu0/view?usp=drivesdk',
          mimeType: 'application/pdf',
        },
      ],
    },
  ],
}

export function getTaxDocuments2025(companyId: string): TaxDocumentFolder[] {
  const folders = TAX_DOCUMENTS_2025[companyId] ?? []
  return folders.filter(f => f.files.length > 0)
}
